openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c/vcalm
paths:
components:
  schemas:
    DeriveCredentialOptions:
      type: object
      additionalProperties: false
      description: Options for specifying how the derived credential is created.
      properties:
        selectivePointers: 
          type: array
          description: An array of JSON pointers specifying the selectively disclosed information.
          items:
            type: string
      example:
        {
          "selectivePointers": ["/credentialSubject/birthCountry"]
        }
