openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c/vcalm
paths:
components:
  schemas:
    VerifyCredentialOptions:
      type: object
      additionalProperties: false
      description: Options for specifying how a credential is verified
      properties:
        returnResults:
          type: boolean
          description: Include results for each verification steps taken in the response, such as verifying individual proofs, statuses and schemas.
        returnProblemDetails:
          type: boolean
          description: Include ProblemDetails errors and warnings in the response.
        returnCredential:
          type: boolean
          description: Should the verified credential be returned in the response? If true, then the verified credential should be returned in the form in which it was verified. If false or not provided, then the verified credential should not be returned.
      example:
        {
          "returnProblemDetails": true,
          "returnCredential": true,
          "returnResults": true
        }